import { UiService, escapeHtml } from './../../services/ui.service';
import { Component, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { KpiCard } from '../../components/kpi-card/kpi-card';
import { CardsSection } from '../../components/cards-section/cards-section';
import { DataTableComponent } from '../../components/data-table/data-table';
import { ChartComponent } from '../../components/charts/charts';

@Component({
  selector: 'app-delay',
  standalone: true,
  imports: [CommonModule, KpiCard, CardsSection, DataTableComponent, ChartComponent],
  templateUrl: './delay.html',
})
export class DelayComponent implements AfterViewInit {
  dataLoaded = false;
  private drill: any = {};
  private palette: any;
  delayColors: string[] = [];
  graceColors: string[] = [];
  frequencyColors: string[] = [];
  escapeHtml = escapeHtml;

  constructor(private ui: UiService) {
    this.palette = this.ui.palette();
    this.delayColors = [this.palette.warn, this.palette.danger];
    this.graceColors = [this.palette.warn, this.palette.danger, this.palette.ok];
    this.escapeHtml = this.ui.escapeHtml;
  }
  async loadData(): Promise<void> {
    try {
      // API Call Here

      this.dataLoaded = true;
    } catch (error) {
      this.ui.toast('Failed to load data');

      this.dataLoaded = false;
    }
  }

  ngAfterViewInit(): void {
    this.loadData();
  }

  cards = [
    {
      label: 'Critical schemes',
      value: 1231,
      cls: 'danger',
      icon: 'exclamation-triangle',
      drill: { status: 'critical' },
      foot: 'critical_report_status = Y',
    },
    {
      label: 'Defaulters',
      value: 345,
      cls: 'danger',
      icon: 'person-x',
      drill: { status: 'defaulter' },
      foot: 'Outside grace or missed cycle',
    },
    {
      label: 'Delayed submissions',
      value: 5667,
      cls: 'warn',
      icon: 'clock-history',
      drill: { status: 'delayed' },
      foot: 'Past expected date',
    },
    {
      label: 'Frequency missed',
      value: 789,
      cls: 'warn',
      icon: 'calendar-x',
      drill: { status: 'freqMissed' },
      foot: 'Full cycles skipped',
    },
    {
      label: 'Within grace period',
      value: 565,
      cls: 'ok',
      icon: 'shield-check',
      drill: { graceStatus: 'Within Grace' },
      foot: 'Late but inside grace',
    },
    {
      label: 'Outside grace period',
      value: 1231,
      cls: 'danger',
      icon: 'shield-exclamation',
      drill: { graceStatus: 'Outside Grace' },
      foot: 'Beyond grace window',
    },
  ];

  //
  delayCategories = ['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Half-Yearly', 'Yearly'];
  delaySeries = [
    {
      name: 'Delayed',
      data: [280, 320, 290, 300, 310, 270],
    },
    {
      name: 'Grace',
      data: [120, 95, 60, 70, 40, 35],
    },
  ];

  graceLabels = ['Within grace', 'Outside grace', 'On time'];
  graceSeries = [120, 95, 60];

  freqLabels = ['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Half-Yearly', 'Yearly'];
  freqSeries = [300, 285, 260, 270, 320, 240];

  onDelayChartClick(event: any) {
    console.log(event);

    this.setDrill({
      frequency: event.category,
    });
  }

  onGraceClick(label: string) {
    switch (label) {
      case 'Within grace':
        this.setDrill({
          graceStatus: 'Within Grace',
        });
        break;

      case 'Outside grace':
        this.setDrill({
          graceStatus: 'Outside Grace',
        });
        break;

      case 'On time':
        this.setDrill({
          graceStatus: 'On Time',
        });
        break;
    }
  }

  onFrequencyClick(label: string) {
    this.setDrill({
      frequency: label,
    });
  }

  private setDrill(patch: any): void {
    this.drill = Object.assign({}, this.drill, patch);
    this.ui.toast('Drilldown applied', 'info');
  }
  private clearDrill(): void {
    this.drill = {};
  }

  valFn(item: any): string {
    return item && item._delayDays != null ? `${item._delayDays}d` : '';
  }

  subFn(item: any): string {
    return item
      ? `${item.dept_name || ''} · ${item.data_freq || item._graceStatus || ''}`
          .trim()
          .replace(/^·\s*/, '')
      : '';
  }

  freqSummary = [
    {
      frequency: 'Daily',
      critical: 154,
      defaulters: 171,
      delayed: 171,
      grace: 121,
    },
    {
      frequency: 'Weekly',
      critical: 139,
      defaulters: 223,
      delayed: 271,
      grace: 48,
    },
    {
      frequency: 'Monthly',
      critical: 128,
      defaulters: 245,
      delayed: 271,
      grace: 26,
    },
    {
      frequency: 'Quarterly',
      critical: 129,
      defaulters: 253,
      delayed: 274,
      grace: 21,
    },
    {
      frequency: 'Half-Yearly',
      critical: 133,
      defaulters: 289,
      delayed: 301,
      grace: 12,
    },
    {
      frequency: 'Yearly',
      critical: 125,
      defaulters: 264,
      delayed: 272,
      grace: 8,
    },
  ];

  tableData = [];
  tableColumns = [
    { title: 'Scheme' },
    { title: 'Department' },
    { title: 'Frequency' },
    { title: 'Expected date' },
    { title: 'Data received' },
    { title: 'Delay days' },
    { title: 'Grace status' },
    { title: 'Freq missed' },
  ];

  topPerformers = [
    {
      project_code: 'PRJ100363',
      project_name: 'PM Surya Ghar',
      display_name: 'PM Surya Ghar — Madhya Pradesh',
      Project_Full_Name: 'PM Surya Ghar — Madhya Pradesh Implementation',
      dept_name: 'Ministry of New and Renewable Energy',
      ministry_name: 'Ministry of New and Renewable Energy',
      State_Name: 'Madhya Pradesh',
      state_code: 'S05',
      district_name: 'Indore',
      dist_code: 'D166',
      KPI_NAME_1: 'PM Surya Ghar — Physical Progress %',
      Data_Granularity: 'Block',
      from_date: '2026-05-02',
      to_date: '2026-06-20',
      latestentrydate: '2026-06-13',
      data_freq: 'Weekly',
      reset_freq: 'Weekly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 25919,
      datafreq_current_value: 25919,
      datafreq_1_value: 12342,
      datafreq_2_value: 5915,
      datafreq_3_value: 6207,
      datafreq_4_value: 8189,
      datafreq_5_value: 7373,
      _isPragati: true,
      _scheme: 'PM Surya Ghar',
      _interval: 7,
      _grace: 3,
      _expectedDate: '2026-06-20T00:00:00.000Z',
      _expectedDateStr: '2026-06-20',
      _delayDays: 0,
      _isDelayed: false,
      _withinGrace: false,
      _outsideGrace: false,
      _graceStatus: 'On Time',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: false,
      _curVal: 25919,
      _prevVal: 12342,
      _delta: 13577,
      _spikePct: 110.00648193161562,
    },
    {
      project_code: 'PRJ100038',
      project_name: 'PM Surya Ghar',
      display_name: 'PM Surya Ghar — Bihar',
      Project_Full_Name: 'PM Surya Ghar — Bihar Implementation',
      dept_name: 'Ministry of New and Renewable Energy',
      ministry_name: 'Ministry of New and Renewable Energy',
      State_Name: 'Bihar',
      state_code: 'S03',
      district_name: 'Patna',
      dist_code: 'D138',
      KPI_NAME_1: 'PM Surya Ghar — Beneficiaries Covered',
      Data_Granularity: 'State',
      from_date: '2024-09-18',
      to_date: '2026-06-17',
      latestentrydate: '2026-03-18',
      data_freq: 'Quarterly',
      reset_freq: 'Quarterly',
      IN_Prod: 'N',
      actual_flag: 'Y',
      critical_report_status: 'Y',
      datafreq_value: 22432,
      datafreq_current_value: 22432,
      datafreq_1_value: 9991,
      datafreq_2_value: 7365,
      datafreq_3_value: 6622,
      datafreq_4_value: 6179,
      datafreq_5_value: 7097,
      _isPragati: true,
      _scheme: 'PM Surya Ghar',
      _interval: 91,
      _grace: 15,
      _expectedDate: '2026-06-17T00:00:00.000Z',
      _expectedDateStr: '2026-06-17',
      _delayDays: 0,
      _isDelayed: false,
      _withinGrace: false,
      _outsideGrace: false,
      _graceStatus: 'On Time',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: true,
      _curVal: 22432,
      _prevVal: 9991,
      _delta: 12441,
      _spikePct: 124.52206986287659,
    },
    {
      project_code: 'PRJ100047',
      project_name: 'PM Surya Ghar',
      display_name: 'PM Surya Ghar — Karnataka',
      Project_Full_Name: 'PM Surya Ghar — Karnataka Implementation',
      dept_name: 'Ministry of New and Renewable Energy',
      ministry_name: 'Ministry of New and Renewable Energy',
      State_Name: 'Karnataka',
      state_code: 'S07',
      district_name: 'Bengaluru Urban',
      dist_code: 'D147',
      KPI_NAME_1: 'PM Surya Ghar — Physical Progress %',
      Data_Granularity: 'District',
      from_date: '2023-04-24',
      to_date: '2026-10-19',
      latestentrydate: '2026-04-20',
      data_freq: 'Half-Yearly',
      reset_freq: 'Half-Yearly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'Y',
      datafreq_value: 20690,
      datafreq_current_value: 20690,
      datafreq_1_value: 11844,
      datafreq_2_value: 7321,
      datafreq_3_value: 10311,
      datafreq_4_value: 6482,
      datafreq_5_value: 7228,
      _isPragati: false,
      _scheme: 'PM Surya Ghar',
      _interval: 182,
      _grace: 20,
      _expectedDate: '2026-10-19T00:00:00.000Z',
      _expectedDateStr: '2026-10-19',
      _delayDays: 0,
      _isDelayed: false,
      _withinGrace: false,
      _outsideGrace: false,
      _graceStatus: 'On Time',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: true,
      _curVal: 20690,
      _prevVal: 11844,
      _delta: 8846,
      _spikePct: 74.68760553866936,
    },
    {
      project_code: 'PRJ101201',
      project_name: 'Ayushman Bharat',
      display_name: 'Ayushman Bharat — Tamil Nadu',
      Project_Full_Name: 'Ayushman Bharat — Tamil Nadu Implementation',
      dept_name: 'Department of Health and Family Welfare',
      ministry_name: 'Ministry of Health and Family Welfare',
      State_Name: 'Tamil Nadu',
      state_code: 'S06',
      district_name: 'Coimbatore',
      dist_code: 'D113',
      KPI_NAME_1: 'Ayushman Bharat — Physical Progress %',
      Data_Granularity: 'State',
      from_date: '2026-06-09',
      to_date: '2026-06-16',
      latestentrydate: '2026-06-15',
      data_freq: 'Daily',
      reset_freq: 'Daily',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'Y',
      datafreq_value: 19900,
      datafreq_current_value: 19900,
      datafreq_1_value: 8751,
      datafreq_2_value: 7842,
      datafreq_3_value: 8295,
      datafreq_4_value: 4174,
      datafreq_5_value: 6268,
      _isPragati: true,
      _scheme: 'Ayushman Bharat',
      _interval: 1,
      _grace: 1,
      _expectedDate: '2026-06-16T00:00:00.000Z',
      _expectedDateStr: '2026-06-16',
      _delayDays: 0,
      _isDelayed: false,
      _withinGrace: false,
      _outsideGrace: false,
      _graceStatus: 'On Time',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: true,
      _curVal: 19900,
      _prevVal: 8751,
      _delta: 11149,
      _spikePct: 127.4025825619929,
    },
    {
      project_code: 'PRJ100383',
      project_name: 'RUSA',
      display_name: 'RUSA — Rajasthan',
      Project_Full_Name: 'RUSA — Rajasthan Implementation',
      dept_name: 'Department of Higher Education',
      ministry_name: 'Ministry of Education',
      State_Name: 'Rajasthan',
      state_code: 'S04',
      district_name: 'Jodhpur',
      dist_code: 'D186',
      KPI_NAME_1: 'RUSA — Beneficiaries Covered',
      Data_Granularity: 'State',
      from_date: '2019-08-03',
      to_date: '2026-08-01',
      latestentrydate: '2025-08-01',
      data_freq: 'Yearly',
      reset_freq: 'Yearly',
      IN_Prod: 'N',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 18715,
      datafreq_current_value: 18715,
      datafreq_1_value: 9195,
      datafreq_2_value: 7547,
      datafreq_3_value: 11159,
      datafreq_4_value: 5007,
      datafreq_5_value: 9836,
      _isPragati: false,
      _scheme: 'RUSA',
      _interval: 365,
      _grace: 30,
      _expectedDate: '2026-08-01T00:00:00.000Z',
      _expectedDateStr: '2026-08-01',
      _delayDays: 0,
      _isDelayed: false,
      _withinGrace: false,
      _outsideGrace: false,
      _graceStatus: 'On Time',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: false,
      _curVal: 18715,
      _prevVal: 9195,
      _delta: 9520,
      _spikePct: 103.53452963567156,
    },
    {
      project_code: 'PRJ100819',
      project_name: 'POSHAN Abhiyaan',
      display_name: 'POSHAN Abhiyaan — Maharashtra',
      Project_Full_Name: 'POSHAN Abhiyaan — Maharashtra Implementation',
      dept_name: 'Ministry of Women & Child Development',
      ministry_name: 'Ministry of Women & Child Development',
      State_Name: 'Maharashtra',
      state_code: 'S02',
      district_name: 'Nashik',
      dist_code: 'D127',
      KPI_NAME_1: 'POSHAN Abhiyaan — Funds Released (Cr)',
      Data_Granularity: 'Block',
      from_date: '2024-11-11',
      to_date: '2026-08-10',
      latestentrydate: '2026-05-11',
      data_freq: 'Quarterly',
      reset_freq: 'Quarterly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'Y',
      datafreq_value: 18030,
      datafreq_current_value: 18030,
      datafreq_1_value: 8146,
      datafreq_2_value: 7853,
      datafreq_3_value: 7559,
      datafreq_4_value: 4905,
      datafreq_5_value: 7337,
      _isPragati: false,
      _scheme: 'POSHAN Abhiyaan',
      _interval: 91,
      _grace: 15,
      _expectedDate: '2026-08-10T00:00:00.000Z',
      _expectedDateStr: '2026-08-10',
      _delayDays: 0,
      _isDelayed: false,
      _withinGrace: false,
      _outsideGrace: false,
      _graceStatus: 'On Time',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: true,
      _curVal: 18030,
      _prevVal: 8146,
      _delta: 9884,
      _spikePct: 121.33562484655044,
    },
    {
      project_code: 'PRJ101513',
      project_name: 'PM Surya Ghar',
      display_name: 'PM Surya Ghar — Tamil Nadu',
      Project_Full_Name: 'PM Surya Ghar — Tamil Nadu Implementation',
      dept_name: 'Ministry of New and Renewable Energy',
      ministry_name: 'Ministry of New and Renewable Energy',
      State_Name: 'Tamil Nadu',
      state_code: 'S06',
      district_name: 'Chennai',
      dist_code: 'D128',
      KPI_NAME_1: 'PM Surya Ghar — Physical Progress %',
      Data_Granularity: 'State',
      from_date: '2024-12-09',
      to_date: '2026-09-07',
      latestentrydate: '2026-06-08',
      data_freq: 'Quarterly',
      reset_freq: 'Quarterly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'Y',
      datafreq_value: 17733,
      datafreq_current_value: 17733,
      datafreq_1_value: 10554,
      datafreq_2_value: 6338,
      datafreq_3_value: 9125,
      datafreq_4_value: 5557,
      datafreq_5_value: 6252,
      _isPragati: false,
      _scheme: 'PM Surya Ghar',
      _interval: 91,
      _grace: 15,
      _expectedDate: '2026-09-07T00:00:00.000Z',
      _expectedDateStr: '2026-09-07',
      _delayDays: 0,
      _isDelayed: false,
      _withinGrace: false,
      _outsideGrace: false,
      _graceStatus: 'On Time',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: true,
      _curVal: 17733,
      _prevVal: 10554,
      _delta: 7179,
      _spikePct: 68.02160318362706,
    },
    {
      project_code: 'PRJ102006',
      project_name: 'Saubhagya',
      display_name: 'Saubhagya — Karnataka',
      Project_Full_Name: 'Saubhagya — Karnataka Implementation',
      dept_name: 'Ministry of Power',
      ministry_name: 'Ministry of Power',
      State_Name: 'Karnataka',
      state_code: 'S07',
      district_name: 'Mysuru',
      dist_code: 'D126',
      KPI_NAME_1: 'Saubhagya — Funds Released (Cr)',
      Data_Granularity: 'Block',
      from_date: '2026-06-08',
      to_date: '2026-06-15',
      latestentrydate: '2026-06-14',
      data_freq: 'Daily',
      reset_freq: 'Daily',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 17075,
      datafreq_current_value: 17075,
      datafreq_1_value: 8480,
      datafreq_2_value: 5143,
      datafreq_3_value: 4399,
      datafreq_4_value: 4524,
      datafreq_5_value: 6606,
      _isPragati: false,
      _scheme: 'Saubhagya',
      _interval: 1,
      _grace: 1,
      _expectedDate: '2026-06-15T00:00:00.000Z',
      _expectedDateStr: '2026-06-15',
      _delayDays: 0,
      _isDelayed: false,
      _withinGrace: false,
      _outsideGrace: false,
      _graceStatus: 'On Time',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: false,
      _curVal: 17075,
      _prevVal: 8480,
      _delta: 8595,
      _spikePct: 101.35613207547169,
    },
  ];
  topDefaulters = [
    {
      project_code: 'PRJ101866',
      project_name: 'PM-KISAN',
      display_name: 'PM-KISAN — Bihar',
      Project_Full_Name: 'PM-KISAN — Bihar Implementation',
      dept_name: 'Department of Agriculture and Farmers Welfare',
      ministry_name: 'Ministry of Agriculture and Farmers Welfare',
      State_Name: 'Bihar',
      state_code: 'S03',
      district_name: 'Muzaffarpur',
      dist_code: 'D184',
      KPI_NAME_1: 'PM-KISAN — Physical Progress %',
      Data_Granularity: 'District',
      from_date: '2017-01-27',
      to_date: '2024-01-26',
      latestentrydate: '2023-01-26',
      data_freq: 'Yearly',
      reset_freq: 'Yearly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 12941,
      datafreq_current_value: 12941,
      datafreq_1_value: 7099,
      datafreq_2_value: 5178,
      datafreq_3_value: 6430,
      datafreq_4_value: 9508,
      datafreq_5_value: 5593,
      _isPragati: false,
      _scheme: 'PM-KISAN',
      _interval: 365,
      _grace: 30,
      _expectedDate: '2024-01-26T00:00:00.000Z',
      _expectedDateStr: '2024-01-26',
      _delayDays: 871,
      _isDelayed: true,
      _withinGrace: false,
      _outsideGrace: true,
      _graceStatus: 'Outside Grace',
      _frequencyMissed: 2,
      _isDefaulter: true,
      _isCritical: false,
      _curVal: 12941,
      _prevVal: 7099,
      _delta: 5842,
      _spikePct: 82.29328074376673,
    },
    {
      project_code: 'PRJ100597',
      project_name: 'Samagra Shiksha',
      display_name: 'Samagra Shiksha — Rajasthan',
      Project_Full_Name: 'Samagra Shiksha — Rajasthan Implementation',
      dept_name: 'Department of School Education and Literacy',
      ministry_name: 'Ministry of Education',
      State_Name: 'Rajasthan',
      state_code: 'S04',
      district_name: 'Jodhpur',
      dist_code: 'D103',
      KPI_NAME_1: 'Samagra Shiksha — Beneficiaries Covered',
      Data_Granularity: 'District',
      from_date: '2017-02-10',
      to_date: '2024-02-09',
      latestentrydate: '2023-02-09',
      data_freq: 'Yearly',
      reset_freq: 'Yearly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 3037,
      datafreq_current_value: 3037,
      datafreq_1_value: 4519,
      datafreq_2_value: 4080,
      datafreq_3_value: 6274,
      datafreq_4_value: 3292,
      datafreq_5_value: 4886,
      _isPragati: false,
      _scheme: 'Samagra Shiksha',
      _interval: 365,
      _grace: 30,
      _expectedDate: '2024-02-09T00:00:00.000Z',
      _expectedDateStr: '2024-02-09',
      _delayDays: 857,
      _isDelayed: true,
      _withinGrace: false,
      _outsideGrace: true,
      _graceStatus: 'Outside Grace',
      _frequencyMissed: 2,
      _isDefaulter: true,
      _isCritical: false,
      _curVal: 3037,
      _prevVal: 4519,
      _delta: -1482,
      _spikePct: -32.794866120823194,
    },
    {
      project_code: 'PRJ100432',
      project_name: 'e-NAM',
      display_name: 'e-NAM — Tamil Nadu',
      Project_Full_Name: 'e-NAM — Tamil Nadu Implementation',
      dept_name: 'Department of Agriculture and Farmers Welfare',
      ministry_name: 'Ministry of Agriculture and Farmers Welfare',
      State_Name: 'Tamil Nadu',
      state_code: 'S06',
      district_name: 'Madurai',
      dist_code: 'D136',
      KPI_NAME_1: 'e-NAM — Targets Achieved',
      Data_Granularity: 'District',
      from_date: '2017-02-13',
      to_date: '2024-02-12',
      latestentrydate: '2023-02-12',
      data_freq: 'Yearly',
      reset_freq: 'Yearly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 8946,
      datafreq_current_value: 8946,
      datafreq_1_value: 10090,
      datafreq_2_value: 12150,
      datafreq_3_value: 10030,
      datafreq_4_value: 10516,
      datafreq_5_value: 10542,
      _isPragati: false,
      _scheme: 'e-NAM',
      _interval: 365,
      _grace: 30,
      _expectedDate: '2024-02-12T00:00:00.000Z',
      _expectedDateStr: '2024-02-12',
      _delayDays: 854,
      _isDelayed: true,
      _withinGrace: false,
      _outsideGrace: true,
      _graceStatus: 'Outside Grace',
      _frequencyMissed: 2,
      _isDefaulter: true,
      _isCritical: false,
      _curVal: 8946,
      _prevVal: 10090,
      _delta: -1144,
      _spikePct: -11.337958374628345,
    },
    {
      project_code: 'PRJ101305',
      project_name: 'POSHAN Abhiyaan',
      display_name: 'POSHAN Abhiyaan — Madhya Pradesh',
      Project_Full_Name: 'POSHAN Abhiyaan — Madhya Pradesh Implementation',
      dept_name: 'Ministry of Women & Child Development',
      ministry_name: 'Ministry of Women & Child Development',
      State_Name: 'Madhya Pradesh',
      state_code: 'S05',
      district_name: 'Bhopal',
      dist_code: 'D118',
      KPI_NAME_1: 'POSHAN Abhiyaan — Targets Achieved',
      Data_Granularity: 'Block',
      from_date: '2017-02-13',
      to_date: '2024-02-12',
      latestentrydate: '2023-02-12',
      data_freq: 'Yearly',
      reset_freq: 'Yearly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 8972,
      datafreq_current_value: 8972,
      datafreq_1_value: 10713,
      datafreq_2_value: 7711,
      datafreq_3_value: 7238,
      datafreq_4_value: 9152,
      datafreq_5_value: 7341,
      _isPragati: false,
      _scheme: 'POSHAN Abhiyaan',
      _interval: 365,
      _grace: 30,
      _expectedDate: '2024-02-12T00:00:00.000Z',
      _expectedDateStr: '2024-02-12',
      _delayDays: 854,
      _isDelayed: true,
      _withinGrace: false,
      _outsideGrace: true,
      _graceStatus: 'Outside Grace',
      _frequencyMissed: 2,
      _isDefaulter: true,
      _isCritical: false,
      _curVal: 8972,
      _prevVal: 10713,
      _delta: -1741,
      _spikePct: -16.251283487351817,
    },
    {
      project_code: 'PRJ101320',
      project_name: 'Digital Land Records',
      display_name: 'Digital Land Records — Madhya Pradesh',
      Project_Full_Name: 'Digital Land Records — Madhya Pradesh Implementation',
      dept_name: 'Department of Land Resources',
      ministry_name: 'Ministry of Rural Development',
      State_Name: 'Madhya Pradesh',
      state_code: 'S05',
      district_name: 'Jabalpur',
      dist_code: 'D133',
      KPI_NAME_1: 'Digital Land Records — Beneficiaries Covered',
      Data_Granularity: 'State',
      from_date: '2017-02-17',
      to_date: '2024-02-16',
      latestentrydate: '2023-02-16',
      data_freq: 'Yearly',
      reset_freq: 'Yearly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 3360,
      datafreq_current_value: 3360,
      datafreq_1_value: 3899,
      datafreq_2_value: 2214,
      datafreq_3_value: 3759,
      datafreq_4_value: 3650,
      datafreq_5_value: 2172,
      _isPragati: false,
      _scheme: 'Digital Land Records',
      _interval: 365,
      _grace: 30,
      _expectedDate: '2024-02-16T00:00:00.000Z',
      _expectedDateStr: '2024-02-16',
      _delayDays: 850,
      _isDelayed: true,
      _withinGrace: false,
      _outsideGrace: true,
      _graceStatus: 'Outside Grace',
      _frequencyMissed: 2,
      _isDefaulter: true,
      _isCritical: false,
      _curVal: 3360,
      _prevVal: 3899,
      _delta: -539,
      _spikePct: -13.824057450628366,
    },
    {
      project_code: 'PRJ102243',
      project_name: 'Swachh Bharat-Gramin',
      display_name: 'Swachh Bharat-Gramin — Madhya Pradesh',
      Project_Full_Name: 'Swachh Bharat-Gramin — Madhya Pradesh Implementation',
      dept_name: 'Department of Drinking Water and Sanitation',
      ministry_name: 'Ministry of Jal Shakti',
      State_Name: 'Madhya Pradesh',
      state_code: 'S05',
      district_name: 'Bhopal',
      dist_code: 'D165',
      KPI_NAME_1: 'Swachh Bharat-Gramin — Beneficiaries Covered',
      Data_Granularity: 'District',
      from_date: '2017-02-20',
      to_date: '2024-02-19',
      latestentrydate: '2023-02-19',
      data_freq: 'Yearly',
      reset_freq: 'Yearly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'Y',
      datafreq_value: 4168,
      datafreq_current_value: 4168,
      datafreq_1_value: 2870,
      datafreq_2_value: 3076,
      datafreq_3_value: 3916,
      datafreq_4_value: 2253,
      datafreq_5_value: 2208,
      _isPragati: false,
      _scheme: 'Swachh Bharat-Gramin',
      _interval: 365,
      _grace: 30,
      _expectedDate: '2024-02-19T00:00:00.000Z',
      _expectedDateStr: '2024-02-19',
      _delayDays: 847,
      _isDelayed: true,
      _withinGrace: false,
      _outsideGrace: true,
      _graceStatus: 'Outside Grace',
      _frequencyMissed: 2,
      _isDefaulter: true,
      _isCritical: true,
      _curVal: 4168,
      _prevVal: 2870,
      _delta: 1298,
      _spikePct: 45.22648083623693,
    },
    {
      project_code: 'PRJ101815',
      project_name: 'PM-KISAN',
      display_name: 'PM-KISAN — West Bengal',
      Project_Full_Name: 'PM-KISAN — West Bengal Implementation',
      dept_name: 'Department of Agriculture and Farmers Welfare',
      ministry_name: 'Ministry of Agriculture and Farmers Welfare',
      State_Name: 'West Bengal',
      state_code: 'S08',
      district_name: 'Kolkata',
      dist_code: 'D133',
      KPI_NAME_1: 'PM-KISAN — Targets Achieved',
      Data_Granularity: 'District',
      from_date: '2017-02-27',
      to_date: '2024-02-26',
      latestentrydate: '2023-02-26',
      data_freq: 'Yearly',
      reset_freq: 'Yearly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 2113,
      datafreq_current_value: 2113,
      datafreq_1_value: 2527,
      datafreq_2_value: 2021,
      datafreq_3_value: 2181,
      datafreq_4_value: 3248,
      datafreq_5_value: 3271,
      _isPragati: false,
      _scheme: 'PM-KISAN',
      _interval: 365,
      _grace: 30,
      _expectedDate: '2024-02-26T00:00:00.000Z',
      _expectedDateStr: '2024-02-26',
      _delayDays: 840,
      _isDelayed: true,
      _withinGrace: false,
      _outsideGrace: true,
      _graceStatus: 'Outside Grace',
      _frequencyMissed: 2,
      _isDefaulter: true,
      _isCritical: false,
      _curVal: 2113,
      _prevVal: 2527,
      _delta: -414,
      _spikePct: -16.383062920459043,
    },
    {
      project_code: 'PRJ100476',
      project_name: 'PMGSY',
      display_name: 'PMGSY — Odisha',
      Project_Full_Name: 'PMGSY — Odisha Implementation',
      dept_name: 'Department of Rural Development',
      ministry_name: 'Ministry of Rural Development',
      State_Name: 'Odisha',
      state_code: 'S10',
      district_name: 'Cuttack',
      dist_code: 'D180',
      KPI_NAME_1: 'PMGSY — Beneficiaries Covered',
      Data_Granularity: 'State',
      from_date: '2017-02-28',
      to_date: '2024-02-27',
      latestentrydate: '2023-02-27',
      data_freq: 'Yearly',
      reset_freq: 'Yearly',
      IN_Prod: 'Y',
      actual_flag: 'N',
      critical_report_status: 'N',
      datafreq_value: 11387,
      datafreq_current_value: 11387,
      datafreq_1_value: 9656,
      datafreq_2_value: 11113,
      datafreq_3_value: 9764,
      datafreq_4_value: 8881,
      datafreq_5_value: 7102,
      _isPragati: false,
      _scheme: 'PMGSY',
      _interval: 365,
      _grace: 30,
      _expectedDate: '2024-02-27T00:00:00.000Z',
      _expectedDateStr: '2024-02-27',
      _delayDays: 839,
      _isDelayed: true,
      _withinGrace: false,
      _outsideGrace: true,
      _graceStatus: 'Outside Grace',
      _frequencyMissed: 2,
      _isDefaulter: true,
      _isCritical: false,
      _curVal: 11387,
      _prevVal: 9656,
      _delta: 1731,
      _spikePct: 17.926677713338858,
    },
  ];
  consecPerformers = [
    {
      _streak: 5,
      project_code: 'PRJ100912',
      project_name: 'MGNREGA',
      display_name: 'MGNREGA — Maharashtra',
      Project_Full_Name: 'MGNREGA — Maharashtra Implementation',
      dept_name: 'Department of Rural Development',
      ministry_name: 'Ministry of Rural Development',
      State_Name: 'Maharashtra',
      state_code: 'S02',
      district_name: 'Nashik',
      dist_code: 'D121',
      KPI_NAME_1: 'MGNREGA — Funds Released (Cr)',
      Data_Granularity: 'State',
      from_date: '2026-06-08',
      to_date: '2026-06-15',
      latestentrydate: '2026-06-14',
      data_freq: 'Daily',
      reset_freq: 'Daily',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 196,
      datafreq_current_value: 196,
      datafreq_1_value: 171,
      datafreq_2_value: 168,
      datafreq_3_value: 114,
      datafreq_4_value: 108,
      datafreq_5_value: 105,
      _isPragati: false,
      _scheme: 'MGNREGA',
      _interval: 1,
      _grace: 1,
      _expectedDate: '2026-06-15T00:00:00.000Z',
      _expectedDateStr: '2026-06-15',
      _delayDays: 0,
      _isDelayed: false,
      _withinGrace: false,
      _outsideGrace: false,
      _graceStatus: 'On Time',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: false,
      _curVal: 196,
      _prevVal: 171,
      _delta: 25,
      _spikePct: 14.619883040935672,
    },
    {
      _streak: 5,
      project_code: 'PRJ102234',
      project_name: 'PM Surya Ghar',
      display_name: 'PM Surya Ghar — Tamil Nadu',
      Project_Full_Name: 'PM Surya Ghar — Tamil Nadu Implementation',
      dept_name: 'Ministry of New and Renewable Energy',
      ministry_name: 'Ministry of New and Renewable Energy',
      State_Name: 'Tamil Nadu',
      state_code: 'S06',
      district_name: 'Coimbatore',
      dist_code: 'D156',
      KPI_NAME_1: 'PM Surya Ghar — Beneficiaries Covered',
      Data_Granularity: 'District',
      from_date: '2026-05-03',
      to_date: '2026-06-21',
      latestentrydate: '2026-06-14',
      data_freq: 'Weekly',
      reset_freq: 'Weekly',
      IN_Prod: 'Y',
      actual_flag: 'N',
      critical_report_status: 'Y',
      datafreq_value: 3571,
      datafreq_current_value: 3571,
      datafreq_1_value: 3453,
      datafreq_2_value: 3117,
      datafreq_3_value: 2092,
      datafreq_4_value: 1846,
      datafreq_5_value: 1739,
      _isPragati: false,
      _scheme: 'PM Surya Ghar',
      _interval: 7,
      _grace: 3,
      _expectedDate: '2026-06-21T00:00:00.000Z',
      _expectedDateStr: '2026-06-21',
      _delayDays: 0,
      _isDelayed: false,
      _withinGrace: false,
      _outsideGrace: false,
      _graceStatus: 'On Time',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: true,
      _curVal: 3571,
      _prevVal: 3453,
      _delta: 118,
      _spikePct: 3.4173182739646686,
    },
    {
      _streak: 5,
      project_code: 'PRJ102377',
      project_name: 'Mission Shakti',
      display_name: 'Mission Shakti — Bihar',
      Project_Full_Name: 'Mission Shakti — Bihar Implementation',
      dept_name: 'Ministry of Women & Child Development',
      ministry_name: 'Ministry of Women & Child Development',
      State_Name: 'Bihar',
      state_code: 'S03',
      district_name: 'Patna',
      dist_code: 'D101',
      KPI_NAME_1: 'Mission Shakti — Targets Achieved',
      Data_Granularity: 'State',
      from_date: '2024-11-27',
      to_date: '2026-08-26',
      latestentrydate: '2026-05-27',
      data_freq: 'Quarterly',
      reset_freq: 'Quarterly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 10484,
      datafreq_current_value: 10484,
      datafreq_1_value: 6417,
      datafreq_2_value: 5557,
      datafreq_3_value: 5474,
      datafreq_4_value: 3644,
      datafreq_5_value: 3428,
      _isPragati: false,
      _scheme: 'Mission Shakti',
      _interval: 91,
      _grace: 15,
      _expectedDate: '2026-08-26T00:00:00.000Z',
      _expectedDateStr: '2026-08-26',
      _delayDays: 0,
      _isDelayed: false,
      _withinGrace: false,
      _outsideGrace: false,
      _graceStatus: 'On Time',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: false,
      _curVal: 10484,
      _prevVal: 6417,
      _delta: 4067,
      _spikePct: 63.37852579086801,
    },
    {
      _streak: 4,
      project_code: 'PRJ100025',
      project_name: 'Saubhagya',
      display_name: 'Saubhagya — Rajasthan',
      Project_Full_Name: 'Saubhagya — Rajasthan Implementation',
      dept_name: 'Ministry of Power',
      ministry_name: 'Ministry of Power',
      State_Name: 'Rajasthan',
      state_code: 'S04',
      district_name: 'Jodhpur',
      dist_code: 'D125',
      KPI_NAME_1: 'Saubhagya — Physical Progress %',
      Data_Granularity: 'Block',
      from_date: '2026-04-28',
      to_date: '2026-06-16',
      latestentrydate: '2026-06-09',
      data_freq: 'Weekly',
      reset_freq: 'Weekly',
      IN_Prod: 'N',
      actual_flag: 'Y',
      critical_report_status: 'Y',
      datafreq_value: 3973,
      datafreq_current_value: 3973,
      datafreq_1_value: 2391,
      datafreq_2_value: 2294,
      datafreq_3_value: 2211,
      datafreq_4_value: 1700,
      datafreq_5_value: 1835,
      _isPragati: false,
      _scheme: 'Saubhagya',
      _interval: 7,
      _grace: 3,
      _expectedDate: '2026-06-16T00:00:00.000Z',
      _expectedDateStr: '2026-06-16',
      _delayDays: 0,
      _isDelayed: false,
      _withinGrace: false,
      _outsideGrace: false,
      _graceStatus: 'On Time',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: true,
      _curVal: 3973,
      _prevVal: 2391,
      _delta: 1582,
      _spikePct: 66.16478460895023,
    },
    {
      _streak: 4,
      project_code: 'PRJ100038',
      project_name: 'PM Surya Ghar',
      display_name: 'PM Surya Ghar — Bihar',
      Project_Full_Name: 'PM Surya Ghar — Bihar Implementation',
      dept_name: 'Ministry of New and Renewable Energy',
      ministry_name: 'Ministry of New and Renewable Energy',
      State_Name: 'Bihar',
      state_code: 'S03',
      district_name: 'Patna',
      dist_code: 'D138',
      KPI_NAME_1: 'PM Surya Ghar — Beneficiaries Covered',
      Data_Granularity: 'State',
      from_date: '2024-09-18',
      to_date: '2026-06-17',
      latestentrydate: '2026-03-18',
      data_freq: 'Quarterly',
      reset_freq: 'Quarterly',
      IN_Prod: 'N',
      actual_flag: 'Y',
      critical_report_status: 'Y',
      datafreq_value: 22432,
      datafreq_current_value: 22432,
      datafreq_1_value: 9991,
      datafreq_2_value: 7365,
      datafreq_3_value: 6622,
      datafreq_4_value: 6179,
      datafreq_5_value: 7097,
      _isPragati: true,
      _scheme: 'PM Surya Ghar',
      _interval: 91,
      _grace: 15,
      _expectedDate: '2026-06-17T00:00:00.000Z',
      _expectedDateStr: '2026-06-17',
      _delayDays: 0,
      _isDelayed: false,
      _withinGrace: false,
      _outsideGrace: false,
      _graceStatus: 'On Time',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: true,
      _curVal: 22432,
      _prevVal: 9991,
      _delta: 12441,
      _spikePct: 124.52206986287659,
    },
  ];
  consecDefaulters = [
    {
      _streak: 5,
      project_code: 'PRJ100978',
      project_name: 'RDSS',
      display_name: 'RDSS — Uttar Pradesh',
      Project_Full_Name: 'RDSS — Uttar Pradesh Implementation',
      dept_name: 'Ministry of Power',
      ministry_name: 'Ministry of Power',
      State_Name: 'Uttar Pradesh',
      state_code: 'S01',
      district_name: 'Varanasi',
      dist_code: 'D187',
      KPI_NAME_1: 'RDSS — Physical Progress %',
      Data_Granularity: 'District',
      from_date: '2018-09-24',
      to_date: '2025-09-22',
      latestentrydate: '2024-09-22',
      data_freq: 'Yearly',
      reset_freq: 'Yearly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 2969,
      datafreq_current_value: 2969,
      datafreq_1_value: 5393,
      datafreq_2_value: 5405,
      datafreq_3_value: 6753,
      datafreq_4_value: 6818,
      datafreq_5_value: 10216,
      _isPragati: true,
      _scheme: 'RDSS',
      _interval: 365,
      _grace: 30,
      _expectedDate: '2025-09-22T00:00:00.000Z',
      _expectedDateStr: '2025-09-22',
      _delayDays: 266,
      _isDelayed: true,
      _withinGrace: false,
      _outsideGrace: true,
      _graceStatus: 'Outside Grace',
      _frequencyMissed: 0,
      _isDefaulter: true,
      _isCritical: false,
      _curVal: 2969,
      _prevVal: 5393,
      _delta: -2424,
      _spikePct: -44.947153717782314,
    },
    {
      _streak: 5,
      project_code: 'PRJ101256',
      project_name: 'Solar Park Scheme',
      display_name: 'Solar Park Scheme — Odisha',
      Project_Full_Name: 'Solar Park Scheme — Odisha Implementation',
      dept_name: 'Ministry of New and Renewable Energy',
      ministry_name: 'Ministry of New and Renewable Energy',
      State_Name: 'Odisha',
      state_code: 'S10',
      district_name: 'Ganjam',
      dist_code: 'D168',
      KPI_NAME_1: 'Solar Park Scheme — Funds Released (Cr)',
      Data_Granularity: 'Block',
      from_date: '2024-07-03',
      to_date: '2026-04-01',
      latestentrydate: '2025-12-31',
      data_freq: 'Quarterly',
      reset_freq: 'Quarterly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'Y',
      datafreq_value: 3460,
      datafreq_current_value: 3460,
      datafreq_1_value: 4975,
      datafreq_2_value: 5705,
      datafreq_3_value: 6418,
      datafreq_4_value: 6650,
      datafreq_5_value: 6836,
      _isPragati: false,
      _scheme: 'Solar Park Scheme',
      _interval: 91,
      _grace: 15,
      _expectedDate: '2026-04-01T00:00:00.000Z',
      _expectedDateStr: '2026-04-01',
      _delayDays: 75,
      _isDelayed: true,
      _withinGrace: false,
      _outsideGrace: true,
      _graceStatus: 'Outside Grace',
      _frequencyMissed: 0,
      _isDefaulter: true,
      _isCritical: true,
      _curVal: 3460,
      _prevVal: 4975,
      _delta: -1515,
      _spikePct: -30.452261306532662,
    },
    {
      _streak: 5,
      project_code: 'PRJ100118',
      project_name: 'PMKSY',
      display_name: 'PMKSY — Uttar Pradesh',
      Project_Full_Name: 'PMKSY — Uttar Pradesh Implementation',
      dept_name: 'Department of Water Resources, River Development and Ganga Rejuvenation',
      ministry_name: 'Ministry of Jal Shakti',
      State_Name: 'Uttar Pradesh',
      state_code: 'S01',
      district_name: 'Gorakhpur',
      dist_code: 'D119',
      KPI_NAME_1: 'PMKSY — Physical Progress %',
      Data_Granularity: 'Block',
      from_date: '2022-12-09',
      to_date: '2026-06-05',
      latestentrydate: '2025-12-05',
      data_freq: 'Half-Yearly',
      reset_freq: 'Half-Yearly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'Y',
      datafreq_value: -2452,
      datafreq_current_value: -2452,
      datafreq_1_value: 2004,
      datafreq_2_value: 2477,
      datafreq_3_value: 3310,
      datafreq_4_value: 3712,
      datafreq_5_value: 4183,
      _isPragati: false,
      _scheme: 'PMKSY',
      _interval: 182,
      _grace: 20,
      _expectedDate: '2026-06-05T00:00:00.000Z',
      _expectedDateStr: '2026-06-05',
      _delayDays: 10,
      _isDelayed: true,
      _withinGrace: true,
      _outsideGrace: false,
      _graceStatus: 'Within Grace',
      _frequencyMissed: 0,
      _isDefaulter: false,
      _isCritical: true,
      _curVal: -2452,
      _prevVal: 2004,
      _delta: -4456,
      _spikePct: -222.3552894211577,
    },
    {
      _streak: 5,
      project_code: 'PRJ100804',
      project_name: 'POSHAN Abhiyaan',
      display_name: 'POSHAN Abhiyaan — West Bengal',
      Project_Full_Name: 'POSHAN Abhiyaan — West Bengal Implementation',
      dept_name: 'Ministry of Women & Child Development',
      ministry_name: 'Ministry of Women & Child Development',
      State_Name: 'West Bengal',
      state_code: 'S08',
      district_name: 'Kolkata',
      dist_code: 'D112',
      KPI_NAME_1: 'POSHAN Abhiyaan — Beneficiaries Covered',
      Data_Granularity: 'State',
      from_date: '2025-11-09',
      to_date: '2026-06-07',
      latestentrydate: '2026-05-08',
      data_freq: 'Monthly',
      reset_freq: 'Monthly',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 0,
      datafreq_current_value: 0,
      datafreq_1_value: 0,
      datafreq_2_value: 5578,
      datafreq_3_value: 5775,
      datafreq_4_value: 7349,
      datafreq_5_value: 7934,
      _isPragati: false,
      _scheme: 'POSHAN Abhiyaan',
      _interval: 30,
      _grace: 7,
      _expectedDate: '2026-06-07T00:00:00.000Z',
      _expectedDateStr: '2026-06-07',
      _delayDays: 8,
      _isDelayed: true,
      _withinGrace: false,
      _outsideGrace: true,
      _graceStatus: 'Outside Grace',
      _frequencyMissed: 0,
      _isDefaulter: true,
      _isCritical: false,
      _curVal: 0,
      _prevVal: 0,
      _delta: 0,
      _spikePct: 0,
    },
    {
      _streak: 5,
      project_code: 'PRJ102171',
      project_name: 'Saubhagya',
      display_name: 'Saubhagya — Madhya Pradesh',
      Project_Full_Name: 'Saubhagya — Madhya Pradesh Implementation',
      dept_name: 'Ministry of Power',
      ministry_name: 'Ministry of Power',
      State_Name: 'Madhya Pradesh',
      state_code: 'S05',
      district_name: 'Jabalpur',
      dist_code: 'D192',
      KPI_NAME_1: 'Saubhagya — Beneficiaries Covered',
      Data_Granularity: 'State',
      from_date: '2026-06-06',
      to_date: '2026-06-13',
      latestentrydate: '2026-06-12',
      data_freq: 'Daily',
      reset_freq: 'Daily',
      IN_Prod: 'Y',
      actual_flag: 'Y',
      critical_report_status: 'N',
      datafreq_value: 0,
      datafreq_current_value: 0,
      datafreq_1_value: 0,
      datafreq_2_value: 4041,
      datafreq_3_value: 4354,
      datafreq_4_value: 5467,
      datafreq_5_value: 7453,
      _isPragati: false,
      _scheme: 'Saubhagya',
      _interval: 1,
      _grace: 1,
      _expectedDate: '2026-06-13T00:00:00.000Z',
      _expectedDateStr: '2026-06-13',
      _delayDays: 2,
      _isDelayed: true,
      _withinGrace: false,
      _outsideGrace: true,
      _graceStatus: 'Outside Grace',
      _frequencyMissed: 2,
      _isDefaulter: true,
      _isCritical: false,
      _curVal: 0,
      _prevVal: 0,
      _delta: 0,
      _spikePct: 0,
    },
  ];
}
